config/routes.rb
PhoebeBoothAntiquesCom::Application.routes.draw do

  root :to => 'home#index'

  resources :invoices, :except => [:new, :edit] do
    resources :line_items, :only => [:edit, :update, :create, :destroy], :shallow => true
    get '/:product_id' => "invoices#create", :as => 'product_setup'
    post '/:contact_id' => "invoices#create", :as => 'contact_setup'
    post '/line_items/:product_id' => 'line_items#create', :as => 'add_product'
  end

  post 'email_invoice/:invoice_id' => "invoices#email_invoice", :as => 'email_invoice'

  post 'groups/:group_id/contacts/:id' => "contact_groups#create", :as => 'apply_contact_to_group'
  post 'subscribers/:contact_id/groups/:id' => "group_contacts#create", :as => 'apply_group_to_contact'
  delete 'groups/:group_id/contacts/:id' => "contact_groups#destroy", :as => 'remove_contact_from_group'
  delete 'subscribers/:contact_id/groups/:id' => "group_contacts#destroy", :as => 'remove_group_from_contact'

  resources :contacts, :path => 'subscribers' do
    resources :notes
  end


  resources :groups

  resources :tooltips, only: [:update], as: 'toggle_tooltips'
  post 'enable_visitor_view' => 'visitor_view#create', :as => :enable_visitor_view
  post 'disable_visitor_view' => 'visitor_view#destroy', :as => :disable_visitor_view
  resources :shows, only: [:index, :create, :destroy] do
    collection do
      post 'sort'
    end
  end

  resources :sliders, except: [:show]

  resources :categories do
    collection do
      post 'sort'
      post 'sort_products'
    end
  end

  resources :configuration

  resources :products do
    resources :images, shallow: true, only: [:create, :destroy]
    resources :keywords, shallow: true, only: [:create, :destroy]
    resources :notes, shallow: true, only: [:create, :destroy]
    collection do
      post 'sort'
    end
  end

  get "home/index"

  resources :users, only: [:edit, :update]
  resources :sessions, only: [:new, :create, :destroy]

  get "change_password" => "users#edit", :as => "change_password"

  get "test_mail" => "admin#test_mail", :as => "test_mail"
  post "send_test_mail" => "admin#send_test_mail", :as => "send_test_mail"


  get "log_in" => "sessions#new", :as => "login"
  get "login" => "sessions#new", :as => "login"
  get "log_out" => "sessions#destroy", :as => "logout"
  get "logout" => "sessions#destroy", :as => "logout"
  get "backend" => "sessions#new", :as => "backend"
  get 'print/:id' => "prints#show", :as => 'print'

  #Navigation Links
  get 'about' => 'home#about', :as => :about
  get 'search' => 'home#search', :as => :search
  get 'new_acquisitions' => 'home#new_acquisitions', :as => :new_acquisitions
  get 'phoebes_finds' => 'home#phoebes_finds', :as => :phoebes_finds
  get 'subscribe' => 'home#subscribe', :as => :subscribe
  post 'subscribe' => 'home#create_contact', :as => :create_contact
  get 'shows' => 'shows#index'

  resources :tasks do
    collection do
      post 'sort'
    end
  end




end

app/models/task.rb
class Task < ActiveRecord::Base
  after_create :set_init_position
  validates :title, presence: true

private

  def set_init_position
    incomplete_tasks = Task.where(:completed => false, :deployed => false)
    task = [] << self
    incomplete_tasks -= task
    update_attributes(:position => 1)
    incomplete_tasks.to_enum.with_index(2) do |task, index|
      task.update_attributes(:position => index)
    end
  end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_filter :require_user
  include Sort

  respond_to :html, :js
  before_filter :require_user

  def index
    @tasks = Task.where(:deployed => false).order(:position)
    respond_with(@tasks)
  end

  def show
    @task = Task.find(params[:id])
    respond_with(@task)
  end

  def new
    @task = Task.new
    respond_with(@task)
  end

  def edit
    @task = Task.find(params[:id])
    respond_with(@task)
  end

  def create
    @task = Task.new(params[:task])
    flash[:notice] = 'Task was successfully created.' if @task.save
    respond_with(@task)
  end

  def update
    @task = Task.find(params[:id])
    flash[:notice] = 'Task was successfully created.' if @task.update_attributes(params[:task])
    respond_with(@task)
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    respond_with(@task)
  end

end

app/helpers/tasks_helper.rb
module TasksHelper

  def show_title(task)
    if task.completed?
      "<s>#{link_to task.title, edit_task_path(task)}</s>".html_safe
    else
      link_to task.title, edit_task_path(task)
    end
  end

  def finish_button(task)
    unless task.completed?
      link_to 'Finish', task_path(task, 'task[completed]' => true), :remote => true,
      :data => {confirm: 'Are you sure?'}, method: :put, :class=> 'btn btn-success'
    end
  end

  def deployed_button(task)
    if task.completed?
      link_to 'Deployed', task_path(task, 'task[deployed]' => true), :remote => true,
      :data => {confirm: 'Are you sure?'}, method: :put, :class=> 'btn btn-warning'
    end
  end

end

app/views/tasks/_form.html.erb
<%= form_for(@task) do |f| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% @task.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :completed %><br />
    <%= f.check_box :completed %>
  </div>
  <div class="field">
    <%= f.label :deployed %><br />
    <%= f.check_box :deployed %>
  </div>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tasks/_task.html.erb
<%= content_tag_for :tr, task do %>
    <td><%= show_title(task) %></td>

    <td>
      <%= finish_button(task) %>
    </td>
    <td>
      <%= deployed_button(task) %>
    </td>

<% end %>

app/views/tasks/edit.html.erb
<%= link_to 'Back', tasks_path %>
<h1>Editing task</h1>
<%= render 'form' %>

app/views/tasks/index.html.erb
<script language="javascript">
  $(document).ready(function(){
    $('#tasks').sortable({
      update: function(event, ui) {
        var tasksOrder = $(this).sortable('toArray');
        $.post( 'tasks/sort', {TasksOrder:tasksOrder});
      }
    });
  });
</script>


<table class="table table-bordered table-striped">
<thead>
  <tr>
    <th>Task</th>
    <th></th>
    <th></th>
  </tr>
</thead>
<tbody id="tasks">
  <%= render @tasks %>
</tbody>
</table>

<br />

<%= link_to 'New Task', new_task_path, :class => "btn btn-primary"%>

app/views/tasks/new.html.erb
<h1>New task</h1>

<%= render 'form' %>

<%= link_to 'Back', tasks_path %>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Completed:</b>
  <%= @task.completed %>
</p>

<p>
  <b>Title:</b>
  <%= @task.title %>
</p>

<p>
  <b>Desc:</b>
  <%= @task.description %>
</p>


<%= link_to 'Edit', edit_task_path(@task) %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/update.js.erb
<% if params[:deployed] == 'true' %>
  $('tr#task_<%= @task.id %>').fadeOut();
<% else %>
  $('tr#task_<%= @task.id%>').replaceWith("<%= escape_javascript(render(@task)) %>");
<% end %>