config/routes.rb
PhoebeBoothAntiquesCom::Application.routes.draw do

  root :to => 'home#index'

  resources :invoices, :except => [:new, :edit] do
    resources :line_items, :only => [:edit, :update, :create, :destroy], :shallow => true
    get '/:product_id' => "invoices#create", :as => 'product_setup'
    post '/:contact_id' => "invoices#create", :as => 'contact_setup'
    post '/line_items/:product_id' => 'line_items#create', :as => 'add_product'
  end

  post 'email_invoice/:invoice_id' => "invoices#email_invoice", :as => 'email_invoice'

  post 'groups/:group_id/contacts/:id' => "contact_groups#create", :as => 'apply_contact_to_group'
  post 'subscribers/:contact_id/groups/:id' => "group_contacts#create", :as => 'apply_group_to_contact'
  delete 'groups/:group_id/contacts/:id' => "contact_groups#destroy", :as => 'remove_contact_from_group'
  delete 'subscribers/:contact_id/groups/:id' => "group_contacts#destroy", :as => 'remove_group_from_contact'

  resources :contacts, :path => 'subscribers' do
    resources :notes
  end


  resources :groups

  resources :tooltips, only: [:update], as: 'toggle_tooltips'
  post 'enable_visitor_view' => 'visitor_view#create', :as => :enable_visitor_view
  post 'disable_visitor_view' => 'visitor_view#destroy', :as => :disable_visitor_view
  resources :shows, only: [:index, :create, :destroy] do
    collection do
      post 'sort'
    end
  end

  resources :sliders, except: [:show]

  resources :categories do
    collection do
      post 'sort'
      post 'sort_products'
    end
  end

  resources :configuration

  resources :products do
    resources :images, shallow: true, only: [:create, :destroy]
    resources :keywords, shallow: true, only: [:create, :destroy]
    resources :notes, shallow: true, only: [:create, :destroy]
    collection do
      post 'sort'
    end
  end

  get "home/index"

  resources :users, only: [:edit, :update]
  resources :sessions, only: [:new, :create, :destroy]

  get "change_password" => "users#edit", :as => "change_password"

  get "test_mail" => "admin#test_mail", :as => "test_mail"
  post "send_test_mail" => "admin#send_test_mail", :as => "send_test_mail"


  get "log_in" => "sessions#new", :as => "login"
  get "login" => "sessions#new", :as => "login"
  get "log_out" => "sessions#destroy", :as => "logout"
  get "logout" => "sessions#destroy", :as => "logout"
  get "backend" => "sessions#new", :as => "backend"
  get 'print/:id' => "prints#show", :as => 'print'

  #Navigation Links
  get 'about' => 'home#about', :as => :about
  get 'search' => 'home#search', :as => :search
  get 'new_acquisitions' => 'home#new_acquisitions', :as => :new_acquisitions
  get 'phoebes_finds' => 'home#phoebes_finds', :as => :phoebes_finds
  get 'subscribe' => 'home#subscribe', :as => :subscribe
  post 'subscribe' => 'home#create_contact', :as => :create_contact
  get 'shows' => 'shows#index'

  resources :tasks do
    collection do
      post 'sort'
    end
  end




end

app/models/group.rb
class Group < ActiveRecord::Base
  validate :title, :presence => true

  has_many :contact_groups, :dependent => :delete_all
  has_many :contacts, :through => :contact_groups

  validates_associated :contact_groups

  scope :excluding_ids, lambda { |ids|
    where(['id NOT IN (?)', ids]) if ids.any?
  }

end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  respond_to :html
  before_filter :require_user

  def index
    @groups = Group.all
    respond_with(@groups)
  end

  def show
    @group = Group.find(params[:id])
    @contacts = @group.contacts
    @non_members = Contact.excluding_ids(@contacts.map(&:id))
    @groups= Group.all
    respond_with(@group)
  end

  def new
    @group = Group.new
    store_referer
    respond_with(@group)
  end


  def edit
    @group = Group.find(params[:id])
    respond_with(@group)
  end

  def create
    @group = Group.new(params[:group])
    if @group.save
      flash[:notice] = 'Group was successfully created.'
    end
    respond_with(@group)
  end

  def update
    @group = Group.find(params[:id])
    add_to_group_if_contact_present

    if @group.update_attributes(params[:group])
      flash[:notice] = 'Group was successfully updated.'
    end
    respond_with(@group)
  end

  def destroy
    @group = Group.find(params[:id])
    @group.destroy
    respond_with(@group)
  end


  private

  def add_to_group_if_contact_present
    if params[:contact_id]
      @contact = Contact.find(params[:contact_id])
      unless @contact.groups.include?(@group)
        @contact.groups << @group
      end
    end
  end


end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_contact.html.haml
= content_tag(:tr, contact) do
  %td= link_to contact.full_name, contact
  %td= link_to contact.email, contact
  %td= contact.address
  %td= contact.city
  %td= contact.state
  %td= contact.zip
  %td.delete.center
    = link_to 'X', remove_contact_from_group_path(@group, contact), :data => {confirm: 'Are you sure?'}, method: :delete

app/views/groups/_form.html.haml
= form_for(@group) do |f|
  - if @group.errors.any?
    #error_explanation
      %h2
        = pluralize(@group.errors.count, "error")
        prohibited this group from being saved:
      %ul
        - @group.errors.full_messages.each do |msg|
          %li= msg
  .field
    = f.label :title
    %br/
    = f.text_field :title
  .actions
    = f.submit

app/views/groups/_group.html.haml
= content_tag(:li, group) do
  = link_to group.title, group

app/views/groups/edit.html.haml
%h1 Editing group
= render 'form'
= link_to 'Show', @group
|
\#{link_to 'Back', groups_path}

app/views/groups/index.html.haml
%h1 Listing groups
%table
  %tr
    %th Title
    %th
    %th
    %th
  - @groups.each do |group|
    %tr
      %td= group.title
      %td= link_to 'Show', group
      %td= link_to 'Edit', edit_group_path(group)
      %td= link_to 'Destroy', group, :data => {confirm: 'Are you sure?'}, method: :delete
%br
= link_to 'New Group', new_group_path

app/views/groups/new.html.haml
%h1 New group
= render 'form'
= link_to 'Back', groups_path

app/views/groups/show.html.haml
.row
  .span12
    %h1
      = @group.title
      Group
.row
  .span2
    .well
      %h2 Groups
      %ul.nav.nav-list
        %li= link_to 'All Subscribers', contacts_path
        %li
          = render @groups
        %li= link_to 'New Group', new_group_path, :class => 'nice small radius button'
    - if @group
      %div
        %ul.nav.nav-list
          %li= link_to 'Delete Group', @group, :data => {confirm: "Are you sure?\n All group members will be lost."}, method: :delete, :class => 'nice small radius button'
  .span10
    %table#contacts.table-bordered
      %thead
        %tr
          %th Name
          %th Email
          %th Address
          %th City
          %th State
          %th Zip
          %th
      %tbody
        = render :partial => "contact", :collection => @group.contacts
    #pager
      %form
        %span.prev ‹ Prev
        %input.pagedisplay{:type => "text"}
        %span.next Next ›
        %select.pagesize
          %option{:selected => "selected", :value => "10"} 10
          %option{:value => "20"} 20
          %option{:value => "30"} 30
          %option{:value => "40"} 40
    = link_to "New Subscriber", new_contact_path, :class => 'nice small radius button'
    - if @group
      = link_to "Add Group Members", "#", :class => 'nice small radius button assign-group-btn'
  - if @group
    #assign-members-modal.reveal-modal
      %h2 Add Members to Group
      %ul
        - @non_members.each do |contact|
          %li= link_to contact.full_name, apply_contact_to_group_path(@group, contact), :method => :post
      %a.close-reveal-modal ×