config/routes.rb
PhoebeBoothAntiquesCom::Application.routes.draw do

  root :to => 'home#index'

  resources :invoices, :except => [:new, :edit] do
    resources :line_items, :only => [:edit, :update, :create, :destroy], :shallow => true
    get '/:product_id' => "invoices#create", :as => 'product_setup'
    post '/:contact_id' => "invoices#create", :as => 'contact_setup'
    post '/line_items/:product_id' => 'line_items#create', :as => 'add_product'
  end

  post 'email_invoice/:invoice_id' => "invoices#email_invoice", :as => 'email_invoice'

  post 'groups/:group_id/contacts/:id' => "contact_groups#create", :as => 'apply_contact_to_group'
  post 'subscribers/:contact_id/groups/:id' => "group_contacts#create", :as => 'apply_group_to_contact'
  delete 'groups/:group_id/contacts/:id' => "contact_groups#destroy", :as => 'remove_contact_from_group'
  delete 'subscribers/:contact_id/groups/:id' => "group_contacts#destroy", :as => 'remove_group_from_contact'

  resources :contacts, :path => 'subscribers' do
    resources :notes
  end


  resources :groups

  resources :tooltips, only: [:update], as: 'toggle_tooltips'
  post 'enable_visitor_view' => 'visitor_view#create', :as => :enable_visitor_view
  post 'disable_visitor_view' => 'visitor_view#destroy', :as => :disable_visitor_view
  resources :shows, only: [:index, :create, :destroy] do
    collection do
      post 'sort'
    end
  end

  resources :sliders, except: [:show]

  resources :categories do
    collection do
      post 'sort'
      post 'sort_products'
    end
  end

  resources :configuration

  resources :products do
    resources :images, shallow: true, only: [:create, :destroy]
    resources :keywords, shallow: true, only: [:create, :destroy]
    resources :notes, shallow: true, only: [:create, :destroy]
    collection do
      post 'sort'
    end
  end

  get "home/index"

  resources :users, only: [:edit, :update]
  resources :sessions, only: [:new, :create, :destroy]

  get "change_password" => "users#edit", :as => "change_password"

  get "test_mail" => "admin#test_mail", :as => "test_mail"
  post "send_test_mail" => "admin#send_test_mail", :as => "send_test_mail"


  get "log_in" => "sessions#new", :as => "login"
  get "login" => "sessions#new", :as => "login"
  get "log_out" => "sessions#destroy", :as => "logout"
  get "logout" => "sessions#destroy", :as => "logout"
  get "backend" => "sessions#new", :as => "backend"
  get 'print/:id' => "prints#show", :as => 'print'

  #Navigation Links
  get 'about' => 'home#about', :as => :about
  get 'search' => 'home#search', :as => :search
  get 'new_acquisitions' => 'home#new_acquisitions', :as => :new_acquisitions
  get 'phoebes_finds' => 'home#phoebes_finds', :as => :phoebes_finds
  get 'subscribe' => 'home#subscribe', :as => :subscribe
  post 'subscribe' => 'home#create_contact', :as => :create_contact
  get 'shows' => 'shows#index'

  resources :tasks do
    collection do
      post 'sort'
    end
  end




end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  respond_to :html
  #before_filter :require_user

  def index
    @sliders = Slider.active.order(:position)
    respond_with(@sliders)
  end

  def about
  end

  def search
    @products = Product.where(:active => true).search(params[:query]) if params[:query]
    respond_with(@products)
  end

  def phoebes_finds
    @products = Product.phoebe_finds.active.order(:position).page params[:page]
    respond_with(@products)
  end

  def subscribe
    @contact = Contact.new
    respond_with(@contact)
  end

  def create_contact

    @contact = Contact.new(params[:contact])
    SubscriberMailer.spam(@contact).deliver if params[:first_name].present?
    respond_to do |format|
      ## [:first_name] is for spam bots - its a hidden field
      ## if a bot fills this out.. not valid and re-render the page.
      if params[:first_name].empty? && @contact.save
        SubscriberMailer.subscribe(@contact).deliver
        format.html { redirect_to category_path(Category.active.sample), notice: 'Thank You... You infomation was successfully saved.' }
      else
        format.html { render action: "subscribe" }
      end
    end
  end

end

app/helpers/home_helper.rb
module HomeHelper

  def slider_magic(slider)
    if slider.product.nil?
      image_tag slider.image_url(:medium), alt: slider.title if slider.image?
    else
      link_to image_tag(slider.image_url(:medium), alt: slider.title ), slider.product
    end
  end

end

app/views/home/_form.html.erb
<%= form_for(@contact, :html =>{:class=> 'nice'}, :url => create_contact_path ) do |f| %>
  <% if @contact.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@contact.errors.count, "error") %> prohibited this subscriber from being saved:</h2>

      <ul>
      <% @contact.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field subscribe">
    <%= f.text_field :email, :class => ' input-text', :placeholder => 'Email' %>
  </div>

  <div class="field subscribe">
    <%= text_field_tag :first_name, nil, :style => "display:none"  %>
  </div>
  <div class="field subscribe">
    <%= f.text_field :first, :class => 'medium input-text', :placeholder => 'First Name'  %>
  </div>
  <div class="field subscribe">
    <%= f.text_field :last, :class => 'medium input-text', :placeholder => 'Last Name' %>
  </div>
  <div class="field subscribe">
    <%= f.text_field :phone, :class => ' input-text', :placeholder => 'Phone' %>
  </div>
  <div class="field subscribe">
    <%= f.text_field :address, :class => ' input-text', :placeholder => 'Address' %>
  </div>
  <div class="field subscribe">
    <%= f.text_field :city, :class => ' input-text', :placeholder => 'City' %>
  </div>
  <div class="field subscribe">
    <%= f.text_field :state, :class => ' input-text', :placeholder => 'State' %>
  </div>
  <div class="field subscribe">
    <%= f.text_field :zip, :class => ' input-text', :placeholder => 'Zip' %>
  </div>
  <div class="field subscribe">
    <%= f.text_field :country, :class => ' input-text', :placeholder => 'Country' %>
  </div>
  <div class="actions">
    <%= f.submit 'Subscribe', :class => 'small white nice button radius'  %>
  </div>
<% end %>

app/views/home/_product.html.erb
<%= content_tag :li do %>
  <span class="block search-photo">
    <%= link_to image_tag(product.image_url(:thumb_100) ), product if product.image? %>
  </span>
  <span class="block search-meta">
    <h4><%= link_to product.item_number, product %> - <%=link_to product.title, product %></h4>
    <%= read_more(product) %>
  </span>
<% end %>

app/views/home/about.html.erb
<div class="contact content-section">
  <%= render 'shared/heading', :heading => 'contact' %>
  <p>Email: <a href="mailto:phoebe@phoebeboothantiques.com" class="green">phoebe@phoebeboothantiques.com</a><br />
    Phone: 917-597-4368
  </p>
</div>

<div class="about content-section">
  <%= render 'shared/heading', :heading => 'about' %>
  <span>
    <%= image_tag('phoebe.jpg') %>
    <a href='wgn.mp4'>Phoebe Booth Antiques featured on WGN Around Town</a>
  </span>

  <p> Phoebe Booth Antiques LLC was founded by Phoebe B. DePree in 2011. The Company specializes in the sale of fine antique English & Irish furniture and objet d'art, focusing on the Queen Anne and Georgian
  periods. Continental furniture is also represented and primarily focuses on authenticity, quality, condition
  and the lasting appeal of each piece. All decorative arts represented are meticulously selected and have
  great character that can only be achieved through age, patination and integrity.</p>

  <p>In addition to selling exceptional European decorative arts from the 17th-19th centuries at antique shows
  around the country, Phoebe Booth Antiques also sources inventory for clients - specific to individual
  style, dimensions and budget.</p>

  <p>Phoebe DePree's personal expertise and invaluable contacts within the art world will provide a reliable
  foundation for collectors of all ages, designers, architects and dealers alike to source and purchase the most
  desirable antiques.</p>

  <p>Mrs. DePree is currently based in Chicago. Prior to founding Phoebe Booth Antiques, she managed,
  for over four years, one of the world's leading decorative arts galleries based in New York. Phoebe DePree
  attended The Sotheby's American Arts program in 2005 and prior to pursuing her passion for decorative
  arts, worked on the Finance Team at The Andrew W. Mellon Foundation and in Equity Research at Morgan
  Stanley.</p>
</div>

app/views/home/contact.html.erb
<%= render 'shared/heading', :heading => 'contact' %>

<div id="contact-page">
  <p>Email: <a href="mailto:phoebe@phoebeboothantiques.com">phoebe@phoebeboothantiques.com</a><br />
    Phone: 917-597-4368
  </p>

  <dl>
    <dt>Upcoming Shows:</dt>
    <dd><a href="http://www.antiquesandgardenshow.com/">The Antiques and Garden Show of Nashville</a>: February 10-12, 2012</dd>
    <dd><a href="http://huntvalleyantiquesshow.org/">Maryland Antiques Show of Hunt Valley</a>: February 23-26, 2012</dd>
    <dd><a href="http://www.stellashows.com/cgi-bin/texis/scripts/showpromo_info/stellashowdetail.html?idnum=ZJD1463&showabb=botanic20020419">
      Chicago Botanic Garden Antiques and Garden Fair
        </a>: April 20-22, 2012
    </dd>
    <dd>Shaia Nantucket Antiques Show: August 10-13, 2012</dd>
  </dl>
</div>

app/views/home/index.html.erb
<div id="slideshow">
	<% @sliders.each do |slider| %>
		<%= slider_magic(slider) %>
	<% end %>
</div>

<script language="javascript">
  $(document).ready(function(){
    $('#slideshow').cycle();
  });
</script>

app/views/home/phoebes_finds.html.erb
<% if current_user %>

	<script language="javascript">
		$(document).ready(function(){
			$('#products').sortable({
				update: function(event, ui) {
					var ProductsOrder = $(this).sortable('toArray');
					$.post( 'products/sort', {ProductsOrder:ProductsOrder});
				}
			});
		});
	</script>
<% end %>



<%= render 'shared/heading', :heading => "PHOEBE'S FINDS" %>


<ul id="products">
  <% if @products.count > 0 %>

  	<% @products.each do |product| %>
  		<%= render product%>
  	<% end %>

  <% else %>

    <li>
    	<h2>Sorry</h2>
    	<p>We are working on the site.  Please check back soon.</p>
    	<p>If you would like to be emailed once we have content available. Click <%= link_to 'here', subscribe_path %></p>
    </li>

  <% end %>
</ul>
<p class="paginate"><%= paginate @products %></p>

app/views/home/search.html.erb
<div id="search-container">
  <%= render 'shared/heading', :heading => 'search' %>
  <div id="search-box">
    <%= form_tag search_path, :method => :get, :class => 'nice' do %>
      <%= content_tag :div, text_field_tag(:query, params[:query], :class => 'input-text'), class: :field %>
      <%= content_tag :div, submit_tag("Find", :class => 'small white nice button radius'), class: :actions %>
    <% end %>
  </div>

  <div id="search-results">
    <% if @products %>
      <p>
        <em>Your search found <b><%=  @products.count.to_s %></b> results.</em>
      </p>

      <ul>
        <%= render partial: 'product', collection: @products %>
      </ul>
    <% end %>
  </div>
</div>

app/views/home/subscribe.html.erb
<%= render 'shared/heading', :heading => 'subscribe' %>

<div id="subscribe">
<p>Please provide your Name and email.  We will be happy to notify you of any special happenings.</p>
  <%= render 'form' %>
</div>

app/views/home/thank_you.html.erb
<h2>Thank You</h2>

<p>Your info has been added.</p>